version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: steamroxo-db
    environment:
      POSTGRES_DB: steamroxo
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: Senha@123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: